version: '3.8'

services:
  backend:
    image: backend
    ports:
      - 8080:8080
    container_name: ex23_backend

  frontend:
    image: frontend
    ports:
      - 5000:5000
    container_name: ex23_frontend
