version: '3.8'

services:
  redis:
    image: redis

  backend:
    image: backend
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080:8080

  frontend:
    image: frontend
    ports:
      - 5000:5000


