version: '3.8'

services:
  redis:
    image: redis
    container_name: ex2_10_redis

  backend:
    image: backend
    environment:
      - REQUEST_ORIGIN=http://localhost/
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    #ports:
    #  - 8080:8080
    container_name: ex2_10_back
    depends_on:
      - db

  frontend:
    image: frontend
    #ports:
    #  - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/
    container_name: ex2_10_front

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    container_name: ex2_10_db

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: ex2_10_nginx
    depends_on:
      - frontend
      - backend

volumes:
  database:



